### ISSUE TITLE
Create temporary wifi access for hack events at City Hall

### ISSUE THREAD

**Issue by samanthawolfe** [c4gnv/meta#2]
- [ ] Open outgoing port 22

- [ ] More generous bandwidth throttle (e. g. 8Mbps instead of 1); so that can use SSH for pulling+pushing code to GitHub

**Comment by stetsonjn** [comment]
Closing -- if we have events at city hall, we have a guest password.

**Comment by stetsonjn** [comment]
How do I close this issue? There is not a Close Issue button....

**Comment by jamessmell** [comment]
I believe I have the power. Here goes...
