### ISSUE TITLE
Project roles

### ISSUE THREAD

**Issue by samanthawolfe** [c4gnv/meta#6]
Establish more defined roles for projects
Develop clearer opportunities for newcomers to plug-in, gain mentorship and guidance, be a part of contributing to project

**Comment by stetsonjn** [comment]
This is an old issue. I agree that we should probably do this too though. I can't close it. Anyone else?

**Comment by jamessmell** [comment]
@stetsonjn do we want to create a new 'issue' or refresh this one?

**Comment by stetsonjn** [comment]
Let's create a new one?

**Comment by jamessmell** [comment]
New issue created
