### ISSUE TITLE
Schedule meetings to kick off 2018

### ISSUE THREAD

**Issue by samanthawolfe** [c4gnv/meta#7]
More structured meetings around specific projects (Josh, Bjorn)
- Manage own schedule per project, in person or virtual, led by project champion, working meetings

Once per month community-oriented meeting (Andrew, Samantha)
- Facebook or Meet-ups, try for a few months then try different social media channels
- Avenue for volunteers to plug into projects then begin participating in project-specific meetings

**Comment by stetsonjn** [comment]
This is a good structure for us to follow. I can schedule out the monthly zoom meetings. What day do we want to do? Second Tuesday? something else?

**Comment by Bjorn248** [comment]
@stetsonjn that works for me! Maybe do a poll on slack asking folks which days work for them?

**Comment by stetsonjn** [comment]
Good idea -- now to figure out how to do a poll on slack.....

**Comment by jamessmell** [comment]
@stetsonjn can we close this issue then?

**Comment by stetsonjn** [comment]
@jamessmell -- yes. first tuesday of the month it is. I will create zooms and meetups.

**Comment by stetsonjn** [comment]
https://www.meetup.com/Code-for-Gainesville

I created meetings for the rest of 2021

**Comment by jamessmell** [comment]
Calling this done for 20 21.
